# Generated by Django 6.0.5 on 2026-05-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telfono',
            new_name='telefono',
        ),
    ]
