# Generated by Django 6.0.5 on 2026-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_telfono_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
