# Generated by Django 6.0.5 on 2026-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total manual'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor con el que reservó'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente'], name='idx_reservas_cliente'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cabana', 'fecha_inicio', 'fecha_fin'], name='idx_reservas_rango_fechas'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_inicio'], name='idx_reservas_fecha_inicio'),
        ),
    ]
