# Generated by Django 6.0.5 on 2026-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_add_total_and_valor_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio personalizado del plan'),
        ),
    ]
