# Generated by Django 6.0.5 on 2026-05-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_add_precio_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_plan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del plan personalizado'),
        ),
    ]
