# Generated by Django 6.0.5 on 2026-05-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_add_nombre_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabana',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto principal'),
        ),
        migrations.CreateModel(
            name='CabanaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL de la imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('alt', models.CharField(blank=True, max_length=100, verbose_name='Texto alternativo')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reservas.cabana')),
            ],
            options={
                'verbose_name': 'Foto de cabaña',
                'verbose_name_plural': 'Fotos de cabañas',
                'ordering': ['orden'],
            },
        ),
    ]
