# Generated by Django 6.0.5 on 2026-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_add_cabana_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabana',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Comodidades, ubicación, etc. Se puede usar saltos de línea para separar párrafos.', verbose_name='Descripción'),
        ),
    ]
