# Generated by Django 6.0.5 on 2026-10-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_add_cabana_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
    ]
